before_install:
  rvm install 2.2.2
language: ruby
rvm:
- 2.2.2
bundler_args: --without production

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - CODECLIMATE_REPO_TOKEN=f048e9b7147365e2d4d864acbca2e2820d218432cd4c741b9592f43512ac5b43 bundle exec rake

# after_script:
#   - gem install codeclimate-test-reporter
#   - bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token: f048e9b7147365e2d4d864acbca2e2820d218432cd4c741b9592f43512ac5b43

