before_install:
  rvm install 2.2.2
language: ruby
rvm:
- 2.2.2
bundler_args: --without production

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - CODECLIMATE_REPO_TOKEN=9d91d9a943aa8336c7a4c0bf8401f01938b9e88235b807ce85d7d7d189f65a58 bundle exec rake

# after_script:
#   - gem install codeclimate-test-reporter
#   - bundle exec codeclimate-test-reporter

addons:
  code_climate:
    repo_token: 9d91d9a943aa8336c7a4c0bf8401f01938b9e88235b807ce85d7d7d189f65a58

